#!/bin/sh

case "$1" in
  start)
    echo "Configuring static IP for eth0..."
    ip addr add 10.0.2.15/24 dev eth0
    ip link set eth0 up
    ip route add default via 10.0.2.2
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    echo "Network configured."
    ;;
  stop)
    echo "Stopping network..."
    ip link set eth0 down
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0